### ISSUE TITLE
Don't work in WordPress 5.2.3

### ISSUE THREAD

**Issue by kina500** [trustpilot/plugin-woocommerce#1]
Trustpilot setting page in wordpress is empty after installation.

**Comment by arunas-stonis** [comment]
We tested it with:
PHP 7.3.10
WordPress 5.2.3
WooCommerce 3.7.0
Storefront 2.5.3

It works as expected.

Could you provide more info regarding the issue:
* what versions do you use?
* what errors do you get?

**Comment by arunas-stonis** [comment]
We are closing this issue as we haven't found any issues and it seems to be working for other customers
