### ISSUE TITLE
Prevent loading frontend JavaScript files if TrustBoxes are not used

### ISSUE THREAD

**Issue by jonathanww** [trustpilot/plugin-woocommerce#3]
Would it be possible to automatically prevent these files from being loaded if TrustBoxes are not used please?

- ../wp-content/plugins/trustpilot-reviews/review/assets/js/headerScript.min.js
- ../wp-content/plugins/trustpilot-reviews/review/assets/js/trustBoxScript.min.js
- https://widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js

**Comment by plainsdrifter** [comment]
We have no plans in the near future to make this feature. But we would be happy to review a PR for this and possibly merge it.

I guess, we are talking here about `trustBoxScript.min.js` and `tp.widget.bootstrap.min.js`, because `headerScript.min.js` would still need to be loaded.
